name: CICD Pipeline

on: 
  push: 
    branches: ["main"]

jobs: 
  compile: 
    runs-on: ubuntu-latest
    
    steps: 
    - uses: actions/checkout@v4
    
    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with: 
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn compile
    
  security-check:
      runs-on: ubuntu-latest
      needs: compile
      
      steps:
        - name: Trivy Installation
          run: | 
              sudo apt update
              sudo apt install -y wget apt-transport-https gnupg lsb-release
              wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo gpg --dearmor -o /usr/share/keyrings/trivy.gpg
              echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/trivy.list > /dev/null
              sudo apt update
              sudo apt install -y trivy
              trivy --version
        
        - name: Trivy File Scan
          run: trivy fs --format table -o fs-report.json
    
        - name: Gitleaks Installation
          run: sudo apt install gitleaks -y
    
        - name: Gitleaks Code Scan
          run: gitleaks detect source . -r gitleaks-report.json -f json
    
          
          
